name: sma_3_2_developers
description: "A Flutter project supporting both online and offline modes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'  # ✅ Agregado para resolver el error

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.7.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  flutter_cache_manager: ^3.3.0
  dio: ^5.3.2
  connectivity_plus: ^6.1.3  # ✅ Actualizado
  media_kit: ^1.0.0
  media_kit_video: ^1.0.0
  media_kit_libs_video: ^1.0.5  # ✅ Version compatible

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/VideoEjemplo.mp4
